### ISSUE TITLE
getting this error every time

### ISSUE THREAD

**Issue by sandeep2194** [gyanprakash0221/LINKEDIN-LEARNING-VIDEOS-DOWNLOAD#1]
2020-12-18 14:07:38,990 asyncio      ERROR    Unclosed connection
client_connection: Connection<ConnectionKey(host='www.linkedin.com', port=443, is_ssl=True, ssl=False, proxy=None, proxy_auth=None, proxy_headers_hash=7026511770396360356)>
Traceback (most recent call last):
  File "linkedin_learning.py", line 246, in <module>
    loop.run_until_complete(process())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 234, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 129, in fetch_course
    data = await resp.json()
  File "/home/sandeep/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.linkedin.com/learning-api/detailedCourses??fields=videos&addParagraphsToTranscript=true&courseSlug=cert-prep-comptia-linux-plus-xko-004/prepare-for-the-compita-linux-plus-certification&q=slugs')

**Comment by djoudi** [comment]
@gyanprakash0221 @sandeep2194 

I have the same issue
